replicaCount: 1

image:
  repository: ghcr.io/stepnine/devops/my_website
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 5001
  name: http

ingress:
  enabled: true
  hosts:
    - host: bogomolove.nginx.int.msk.drunkbatya.com
      paths:
        - path: /
          pathType: Prefix
  tls: []  
