name: CI Pipeline 

on:
  push: 
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 

        
      - name: gogogo
        run: docker build -t ghcr.io/stepnine/devops/myapp:latest .
      - name: final
        run: docker push -t ghcr.io/stepNine/devops/myapp:latest .
        
