name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV


      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./my_website              
          file: ./my_website/Dockerfile    
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/stepnine/devops:latest
      
